import type { Vendor } from "@/table-types/vendor-table-types";

export const dummyVendors: Vendor[] = [
  {
    id: "1",
    name: "Riddhi Sharma",
    phone: "9876543210",
    category: "Electronics",
    subCategory: "Mobiles",
    membersgip: "Premium",
    timeCreated: "2025-09-10",
    status: "Active",
  },
  {
    id: "2",
    name: "Amit Verma",
    phone: "9123456789",
    category: "Clothing",
    subCategory: "Men’s Wear",
    membersgip: "Standard",
    timeCreated: "2025-09-12",
    status: "Inactive",
  },
  {
    id: "3",
    name: "Sneha Gupta",
    phone: "9988776655",
    category: "Food & Beverages",
    subCategory: "Snacks",
    membersgip: "Gold",
    timeCreated: "2025-09-14",
    status: "Active",
  },
  {
    id: "4",
    name: "Rajesh Kumar",
    phone: "9871234560",
    category: "Home & Furniture",
    subCategory: "Kitchen",
    membersgip: "Basic",
    timeCreated: "2025-09-15",
    status: "Inactive",
  },
  {
    id: "5",
    name: "Priya Singh",
    phone: "9812345678",
    category: "Beauty & Personal Care",
    subCategory: "Cosmetics",
    membersgip: "Premium",
    timeCreated: "2025-09-16",
    status: "Active",
  },
];
