import type { Vendor } from "@/table-types/vendor-table-types";

export const dummyVendors: Vendor[] = [

  {
    id: "1",
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "9876543210",
    category: "Electronics",
    subCategory: "Mobile Phones",
    membership: "Premium",
    alternative_phone_number: "9123456789",
    address: "12 MG Road, Guwahati",
    address_proof: "aadhar_card.pdf",
    id_proof: "pan_card.pdf",
    city_id: "C001",
    district_id: "D001",
    state_id: "S001",
    status: "active",
    location_id: "L001",
    pin_code_id: "781001",
    current_membership_id: "M001",
  },
  {
    id: "2",
    name: "Ananya Gupta",
    email: "ananya.gupta@example.com",
    phone: "9988776655",
    category: "Clothing",
    subCategory: "Women’s Wear",
    membership: "Basic",
    alternative_phone_number: null,
    address: "45 Park Street, Kolkata",
    address_proof: "voter_id.pdf",
    id_proof: null,
    city_id: "C002",
    district_id: "D002",
    state_id: "S002",
    status: "inactive",
    location_id: "L002",
    pin_code_id: "700016",
    current_membership_id: null,
  },
  {
    id: "3",
    name: "Sandeep Kumar",
    email: "sandeep.kumar@example.com",
    phone: "9012345678",
    category: "Food & Beverages",
    subCategory: "Bakery",
    membership: "Gold",
    alternative_phone_number: "9811122233",
    address: "22 Banjara Hills, Hyderabad",
    address_proof: null,
    id_proof: "driving_license.pdf",
    city_id: "C003",
    district_id: "D003",
    state_id: "S003",
    status: "active",
    location_id: "L003",
    pin_code_id: "500034",
    current_membership_id: "M003",
  },
  {
    id: "4",
    name: "Meena Iyer",
    email: "meena.iyer@example.com",
    phone: "8899776655",
    category: "Home Decor",
    subCategory: "Furniture",
    membership: "Standard",
    alternative_phone_number: null,
    address: "89 Brigade Road, Bangalore",
    address_proof: "ration_card.pdf",
    id_proof: "passport.pdf",
    city_id: "C004",
    district_id: "D004",
    state_id: "S004",
    status: "suspended",
    location_id: "L004",
    pin_code_id: "560025",
    current_membership_id: "M004",
  },
];



